on: [release]

name: PROD - Deploy Azure Resource
jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      # Checkout code
    - uses: actions/checkout@v2

      # Deploy Resource to ACR
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        az bicep publish --file main.bicep --target br:${{ secrets.REGISTRY_LOGIN_SERVER }}/bicep/modules/app:${{ github.sha }}